language: python
python:
- '3.5'
install:
- pip install .
- pip install -r requirements.txt
- pip install pyflakes
- pip install coveralls
before_script:
- make pyflakes
script:
- make test
- make coverage
after_success:
  coveralls